[package]
name = "julia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "2.0.0"
num-complex = "0.4.4"
image = "0.25.0"
itertools = "0.12.0"